### PR TITLE
⬆️ SecretManagement 1.1.0 Compatibility

### PR DESCRIPTION
**Pull request by JustinGrote**
SecretManagement 1.1.0 moves the vault extension into its own runspace and adds a new Unlock-SecretVault mechanism. This adds support for that new operating model.

### CODE REVIEW

**Comment by JustinGrote** [comment]
@Callidus2000 if you can find out why Write-PSFMessage -Error has different behavior than write-error that causes the trap tests to fail I'd appreciate it, otherwise I'm just going to revert them to write-error for now.

**Comment by Callidus2000** [comment]
@JustinGrote The PSFramework works with an [Opt-In-Exception](https://psframework.org/documentation/documents/psframework/flow-control/opt-in-exceptions.html) concept. Because of this `Write-PSFMessage -Level Error` does not throw exceptions/trigger traps. If this should be necessary/desired a few more changes have to be implemented, more details documented by Fred in the documentation.

**Comment by Callidus2000** [comment]
Hi,
any idea when the new module version will be build and submitted?

**Comment by JustinGrote** [comment]
> Hi,
> any idea when the new module version will be build and submitted?

Still failing tests I haven't gotten around to troubleshooting yet.

**Review by OranguTech — COMMENTED** [review]
Microsoft.Powershell.SecretManagement 1.1.0 GA has been released, FWIW.

https://devblogs.microsoft.com/powershell/announcing-secretmanagement-1-1-ga/

**Comment by JustinGrote** [comment]
Yeah I'm aware, this is a volunteer project and I only have so much time in the day, if you want to sponsor me to pay to get it done I can dedicate more time to it, or you can help contribute to fix the bugs so that the tests pass :)

**Comment by Callidus2000** [comment]
Taking a look at it, first encounter with GitHub actions for me....
`Press Build / Build` is already working, the `Press Build / Test` is ongoing... Did miss that not all pester tests are located within the test-folder....

**Comment by Callidus2000** [comment]
Yargh...
In my fork the build workflow runs perfectly, tests work everywhere but under windows os.
https://github.com/Callidus2000/SecretManagement.KeePass/runs/3371843015?check_suite_focus=true

image

If I comment out the windows os everything runs.
https://github.com/Callidus2000/SecretManagement.KeePass/actions/runs/1146988885
image

For me currently a mystery is why the tests fail on windows. I've eliminated all bugs caused by my lazy PSFramework integration (and missing the other pester test files), all tests run on my windows system.
Either the windows os should be excluded from the workflow or I need more time for a GitHub Actions deep dive....

**Comment by JustinGrote** [comment]
Looks like PSFramework hasn't been added to the Press prerequisite module list so it's not downloading it.
image

**Comment by Callidus2000** [comment]
Any hint where to do this?

**Comment by JustinGrote** [comment]
> Any hint where to do this?

.config/RequiredModules.ps1

**Comment by Callidus2000** [comment]
Nope, this one I'd already found:
https://github.com/Callidus2000/SecretManagement.KeePass/blob/fix/SecretManagement1.1.0/.config/RequiredModules.psd1
```Powershell
@{
    'Microsoft.Powershell.SecretManagement' = '1.1.0'
    'PowerConfig'                           = '0.1.3'
    'PSFramework'                           = '1.6.205'
}
```

**Comment by JustinGrote** [comment]
@Callidus2000  I'm just saying that's why it's failing in this PR currently.

**Comment by Callidus2000** [comment]
Hi @JustinGrote, misunderstood you...

I want to help to get rid of the errors. In order to do so I created a new fork and fixed everything but the workflow tests under Windows. I do not understand why as (now all) the pester tests work fine my Win10 real system.

**Comment by JustinGrote** [comment]
@Callidus2000 what looks like is happening is the pester tests are run in a separate standalone job for some tests, and secretmanagement is not getting loaded into that job. It's looking pretty good otherwise, I imagine I can fix that pretty quick tonight. Thanks for your hard work on this.

**Comment by JustinGrote** [comment]
@Callidus2000 it's the Windows Powershell (5.1) tests that are failing
image

**Comment by JustinGrote** [comment]
There appears to be a recursion issue with running the WInPS tests in a Windows Powershell Job, doesnt happen when run as a main process though. I'll see if I can workaround it for now and fully fix later.

**Comment by JustinGrote** [comment]
I'm pretty sure the problem is the PSModulePath isn't carrying into the 5.1 job
image

**Comment by JustinGrote** [comment]
The problem is a transient stacktrace problem when doing winPS tests. I've disabled the tests with a warning for now since they all pass locally and will merge.
https://github.com/pester/Pester/issues/1974

**Comment by JustinGrote** [comment]
@Callidus2000 thanks for your patience on this.

**Comment by Callidus2000** [comment]
@JustinGrote No problem, I fully understand the problem of missing free times for personal projects. I'm glad that the problems had some base within the underlying/used eco system ;-)

**Pull request merged**
